General bash script cleanup

diff --git a/modules/puppet-auto-update/files/puppet-git-run b/modules/puppet-auto-update/files/puppet-git-run
--- a/modules/puppet-auto-update/files/puppet-git-run
+++ b/modules/puppet-auto-update/files/puppet-git-run
@@ -2,24 +2,23 @@
 #########################################################################
 ##   This file is controlled by Puppet - changes will be overwritten   ##
 #########################################################################
-#Exit if any unset variables are used, if any command returns an error
-set -o nounset
-set -o errexit
+set -e
 
 LOGFILE="/var/log/puppet-git/puppet-git-run"
 function log {
-    echo $(date --rfc-3339=ns)" ${1}"
-    echo $(date --rfc-3339=ns)" ${1}" >> $LOGFILE
+    echo $(date --rfc-3339=ns)" ${1}" | tee -a $LOGFILE
 }
 
-log 'puppet-git-run called'
+log $0' called'
 
-if /usr/bin/[ `ps a | grep puppe[t] | wc -l` = 0 ]; then
-    log 'ABORTING due to puppet already in process list'
+if ps -e | grep puppe[t]; then
+    log 'ABORTING due to puppet already being in process list'
     exit 4;
 fi
 
-/usr/bin/puppet apply -l $LOGFILE --modulepath=/etc/puppet-git/modules /etc/puppet-git/manifests/site.pp -vv
+unbuffer /usr/bin/puppet apply -vv
+    --modulepath=/etc/puppet-git/modules /etc/puppet-git/manifests/site.pp \
+    2>&1 | tee -a $LOGFILE
 
 log 'puppet-git-run complete'
 exit 0
